version: '3'
services:
  postgres:
    environment:
      - TZ=Asia/Shanghai
    image: postgres:latest    
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  progresDB:

 

