import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { routing } from "@/src/i18n/routing";
import "@ant-design/v5-patch-for-react-19";
import { getMessages, setRequestLocale } from "next-intl/server";

import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Test",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const { locale } = await params;
  console.log(locale, "locale");
  // Enable static rendering
  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <SessionProvider>
          <AntdRegistry>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </AntdRegistry>
        </SessionProvider>

        <Toaster />
      </body>
    </html>
  );
}
